export const PRODUCTS = [
  // ── ANTIQUES ──────────────────────────────────
  {
    id: 1,
    name: "Vintage Leather Briefcase",
    emoji: "🧳",
    listPrice: 500,
    minPrice: 270,
    targetPrice: 390,
    category: "Antiques",
    description: "A rare 1960s leather briefcase in mint condition",
  },
  {
    id: 2,
    name: "Rare Pocket Watch",
    emoji: "⌚",
    listPrice: 800,
    minPrice: 420,
    targetPrice: 630,
    category: "Antiques",
    description: "18k gold pocket watch from 1890s Switzerland",
  },
  {
    id: 3,
    name: "Victorian Writing Desk",
    emoji: "🪑",
    listPrice: 1500,
    minPrice: 850,
    targetPrice: 1200,
    category: "Antiques",
    description: "Solid mahogany writing desk from Victorian England",
  },

  // ── HOME DECOR ─────────────────────────────────
  {
    id: 4,
    name: "Handmade Persian Carpet",
    emoji: "🪞",
    listPrice: 1200,
    minPrice: 680,
    targetPrice: 950,
    category: "Home Decor",
    description: "Hand-knotted Persian carpet, 200 years old",
  },
  {
    id: 5,
    name: "Murano Glass Chandelier",
    emoji: "💡",
    listPrice: 2000,
    minPrice: 1100,
    targetPrice: 1600,
    category: "Home Decor",
    description: "Handblown Murano glass chandelier from Venice Italy",
  },
  {
    id: 6,
    name: "Japanese Bonsai Tree",
    emoji: "🌳",
    listPrice: 600,
    minPrice: 320,
    targetPrice: 480,
    category: "Home Decor",
    description: "50 year old hand-trained Japanese maple bonsai",
  },

  // ── COLLECTIBLES ───────────────────────────────
  {
    id: 7,
    name: "First Edition Book Set",
    emoji: "📚",
    listPrice: 950,
    minPrice: 520,
    targetPrice: 740,
    category: "Collectibles",
    description: "First edition Sherlock Holmes complete collection",
  },
  {
    id: 8,
    name: "Signed Cricket Bat",
    emoji: "🏏",
    listPrice: 750,
    minPrice: 400,
    targetPrice: 580,
    category: "Collectibles",
    description: "Signed by the 1983 World Cup winning Indian team",
  },
  {
    id: 9,
    name: "Vintage Vinyl Records",
    emoji: "🎵",
    listPrice: 450,
    minPrice: 240,
    targetPrice: 350,
    category: "Collectibles",
    description: "Original Beatles collection — all 12 studio albums",
  },
  {
    id: 10,
    name: "Rare Stamp Collection",
    emoji: "📮",
    listPrice: 1100,
    minPrice: 600,
    targetPrice: 850,
    category: "Collectibles",
    description: "19th century rare stamps from 30 countries",
  },

  // ── APPLIANCES ─────────────────────────────────
  {
    id: 11,
    name: "Artisan Espresso Machine",
    emoji: "☕",
    listPrice: 650,
    minPrice: 350,
    targetPrice: 510,
    category: "Appliances",
    description: "Italian handcrafted espresso machine limited edition",
  },
  {
    id: 12,
    name: "Handcrafted Tandoor Oven",
    emoji: "🔥",
    listPrice: 900,
    minPrice: 500,
    targetPrice: 700,
    category: "Appliances",
    description: "Traditional clay tandoor oven from Rajasthan",
  },

  // ── JEWELRY ────────────────────────────────────
  {
    id: 13,
    name: "Antique Silver Necklace",
    emoji: "📿",
    listPrice: 1300,
    minPrice: 720,
    targetPrice: 1000,
    category: "Jewelry",
    description: "Handcrafted Rajasthani silver necklace 100 years old",
  },
  {
    id: 14,
    name: "Emerald Ring",
    emoji: "💍",
    listPrice: 2500,
    minPrice: 1400,
    targetPrice: 2000,
    category: "Jewelry",
    description: "Colombian emerald set in 22k gold vintage ring",
  },

  // ── TECH ───────────────────────────────────────
  {
    id: 15,
    name: "Vintage Camera",
    emoji: "📷",
    listPrice: 700,
    minPrice: 380,
    targetPrice: 550,
    category: "Tech",
    description: "1970s Leica M3 film camera in working condition",
  },
];